import "./globals.css";
import { manrope } from "../../public/assets/font/font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Audiophile ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.variable}>{children}</body>
    </html>
  );
}
